### ISSUE TITLE
Update Changelog

### ISSUE THREAD

**Issue by RodrigoTomeES** [sladg/nextjs-lambda#32]
Hi,

Could you update the changelog file to reflect the last updates?

Thanks for your work!

**Comment by sladg** [comment]
Hey! Changelog is out of date as I ditched `@auto-it` ecosystem due to being overly complex. Any recommendation on generating changelog from tags? Cheers!

**Comment by RodrigoTomeES** [comment]
Hi,

I never use a pipeline to generate a changelog I always create it manually 😅, so I can't recommend it nothing,

Sorry

**Comment by sladg** [comment]
Hey! Changelog is back!

It's not 100% polished yet, I need to make it to include latest version as well as authors and some other useful things, but I believe this can be closed for now.
