### ISSUE TITLE
Bundle image handler with Sharp

### ISSUE THREAD

**Issue by sladg** [sladg/nextjs-lambda#45]
Existing implementation was error prone, creating unnecessary complexity and layers.
There needs to be easier way how to bundle image handler and include Sharp for Lambda as well.

Currently using Squoosh for image handling, which is not recommended for production use with Vercel.

**Comment by khuezy** [comment]
I'd be interested in how you're bundling sharp into the lambda Function/NodejsFunction. Sharp spawns a child process and executes the sharp binary, it might not be possible to bundle the sharp code into the function.

**Comment by sladg** [comment]
Next's built-in image handler will be replaced by custom solution as it ultimately sucks.
Bundling is overly complicated, passing binaries does not work as expected, hacking all around is needed.

Related to #64

Will be optionally secured by providing allowed image sources.
Expected in version 4 (in couple of days).

**Comment by sladg** [comment]
As of v4, image optimizer was moved to separate package.
Changes: https://github.com/sladg/nextjs-lambda/compare/release/v3.22.0...v4.0.0
New optimizer: https://github.com/sladg/imaginex-lambda
