### ISSUE TITLE
Bundled `image-handler` isn't respecting allowed `remotePatterns` / `domains`

### ISSUE THREAD

**Issue by fabiob** [sladg/nextjs-lambda#48]
My Next.js stores images on a CDN, which requires me to display them using their absolute URLs. However, the bundled image-handler refuses to work with them, as it was built before reading my `next.config.js`.

**Comment by sladg** [comment]
Hey! 
Any chance you can provide me with minimal repo example?

**Comment by sladg** [comment]
@fabiob 👋

**Comment by sladg** [comment]
Considering inactivity and the fact that this package renders the use of external CDN pretty much pointless (we are using Cloudfront + S3), I'm closing this issue.
