### ISSUE TITLE
 Specified target is invalid. Provided: "standalone" should be one of server, serverless, experimental-serverless-trace

### ISSUE THREAD

**Issue by sennett** [sladg/nextjs-lambda#51]
Thanks for this project.  I'm having trouble running `next build` with `target: 'standalone'`.  next.config.js is:

```
module.exports = {
  async redirects() {
    return [
      {
        source: '/town/:slug',
        destination: '/towns/:slug',
        permanent: true,
      },
    ]
  },
  output: 'standalone',
  target: 'standalone',
  compress: false,
}
```

When I run `next built` I get the following output:

`Error: Specified target is invalid. Provided: "standalone" should be one of server, serverless, experimental-serverless-trace`

Running `npx --package @sladg/nextjs-lambda next-utils pack` without this results in `Process failed with error: Error: Folder: /Users/<project root>/.next/standalone does not exist!`

From the [next docs](https://github.com/vercel/next.js/blob/canary/packages/next/server/config-shared.ts#L158) it seems we can have `output: 'standalone',`?  But this doesn't seem to work either, or where am I going wrong?  Thanks.

**Comment by sladg** [comment]
Hey! just remove `target` it's not used, we just need to have `output` configured.

**Comment by sladg** [comment]
I will fix documentation in a minute, sorry for confusion.

**Comment by sladg** [comment]
Fixed in `v3.20.4`

**Comment by sladg** [comment]
Next13 works fine for you however 12 did not output the directory? 🤔 that's sus

**Comment by sennett** [comment]
It was Next 12.1 - maybe there was something messed up in my yarn.lock.
