### ISSUE TITLE
Cloudwatch alerts

### ISSUE THREAD

**Issue by sennett** [sladg/nextjs-lambda#55]
How do you guys configure cloudwatch alerts without Cloudformation config drift?  Right now my plan is to fork the repo and add things to `NextStandaloneStack`, but is there something you do instead?  I'm trying to get alerts when there are HTTP errors over a certain threshold, for both Next routes and image optimisation.

**Comment by sennett** [comment]
I see that AWS does not automatically include linked resources in the Cloudformation stack so I can bolt these on.  As long as I don't edit resources created as part of the stack itself, there is no drift.

**Comment by sladg** [comment]
Hey! Feel free to create your CDK stack from `lib/cdk/stack.ts`. I would deem alerts to be over the basic configuration so I don't plan to add them to the repository.
