### ISSUE TITLE
Is middleware supported?

### ISSUE THREAD

**Issue by khuezy** [sladg/nextjs-lambda#59]
I see a middleware checkmark in the list of features, but when I deploy the example: https://github.com/vercel/next.js/tree/canary/examples/middleware, it doesn't actually work.

Edit: it does work when you reload the browser, but using `<Link />`, it does not work.

**Comment by sladg** [comment]
Hey! Yes, we tested `middleware.ts` on Next@12.3, and redirects worked fine, moreover, redirects also work by specifying them in `next.config.js`. Can you share your expected result compared to the current state? `<Link/>` is not used in `middleware.ts,` so I'm not 100% sure where to look.

**Comment by khuezy** [comment]
Hi thanks for replying, redirect is working for me now. I must have messed up somewhere.
