### ISSUE TITLE
'STACK_NAME' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by talaikis** [sladg/nextjs-lambda#65]
`'STACK_NAME' is not recognized as an internal or external command` on Windows. Probably `STACK_NAME=${stackName}`, should be changed to `cross-env STACK_NAME=${stackName},` to support other OSs.

**Comment by sladg** [comment]
Fixed in version 5.1.5.
See: https://github.com/sladg/nextjs-lambda/compare/v5.1.4...v5.1.5
