### ISSUE TITLE
Specify Profile for CDK to use

### ISSUE THREAD

**Issue by bounds** [sladg/nextjs-lambda#75]
Hoping there would be a deploy flag for choosing an AWS profile from `~/.aws/credentials`

Bit of a pain to modify `[profile.default]`to get this going. 

Maybe there's a better way?

**Comment by sladg** [comment]
I would suggest giving a shot to https://www.npmjs.com/package/aws-profile-switcher :)

**Comment by bounds** [comment]
But CDK already has a flag you can forward!

**Comment by bounds** [comment]
Alright I'll figure it out thanks!

**Comment by bounds** [comment]
Opened PR #76

**Comment by sladg** [comment]
Merged, closing, thank you for PR!
