### ISSUE TITLE
Support for Cloudfront Alternate Domain Names

### ISSUE THREAD

**Issue by pinarruiz** [sladg/nextjs-lambda#79]
Adding an option like `--alternateDomainNames` where domain names will be fed in a comma separated manner, or reading multiple entries of the option.

As far as i know there is no way of doing this.

**Comment by sladg** [comment]
Good point, currently it's possible only with extending CDK and altering the stack definition manually.
Will take a look at it, should be done within few days.

**Comment by sladg** [comment]
This has been released in version 7.0.0.
Use `--domainNames example.com,other.domain.com,extra.net` in CLI command.
