### ISSUE TITLE
Process failed with error: Error: Public folder assets must be nested in public/assets folder

### ISSUE THREAD

**Issue by iamvade** [sladg/nextjs-lambda#86]
Use case:
NextJS 13 blank project
standalone and compress options on next.config.js added

"Process failed with error: Error: Public folder assets must be nested in public/assets folder"
Getting error above when run "npx --package @sladg/nextjs-lambda cli pack" command.

**Comment by davulrich** [comment]
You need to create **assets** folder directly in the **public** folder and move all content of the **public** folder into it.
![image](https://user-images.githubusercontent.com/46351885/234195526-9cf2e922-06c1-4897-9a30-ed1ab2300419.png)

In [Readme](https://github.com/sladg/nextjs-lambda/blob/master/README.md#packaging) file you can find what's reason behind it.

**Comment by sladg** [comment]
Exactly as @davulrich stated.
